#pragma once

// Exact same-name Android NDK/system candidates observed in the authorized
// Angry Birds v1.0 import set.  The runtime still registers ARM32 adapters for
// these names: an arm64 dlsym address is not callable by an ARM32 guest.

#include "compat_runtime/shim_registry.hpp"

#include <array>
#include <string>
#include <vector>

namespace radek::compat_runtime::ndk_import_catalog {

struct Provider {
    const char *symbol;
};

inline constexpr std::array<Provider, 181> kProviders{{
    {"__ZSt9terminatev"},
    {"__ZTVN10__cxxabiv117__class_type_infoE"},
    {"__ZTVN10__cxxabiv119__pointer_type_infoE"},
    {"__ZTVN10__cxxabiv120__si_class_type_infoE"},
    {"__ZTVN10__cxxabiv121__vmi_class_type_infoE"},
    {"__ZdaPv"},
    {"__ZdlPv"},
    {"__Znam"},
    {"__Znwm"},
    {"___cxa_allocate_exception"},
    {"___cxa_atexit"},
    {"___cxa_begin_catch"},
    {"___cxa_end_catch"},
    {"___cxa_pure_virtual"},
    {"___cxa_throw"},
    {"_abort"},
    {"_acosf"},
    {"_asinf"},
    {"_atan2"},
    {"_atan2f"},
    {"_atanf"},
    {"_ceilf"},
    {"_clearerr"},
    {"_clock"},
    {"_close"},
    {"_cos"},
    {"_cosf"},
    {"_coshf"},
    {"_difftime"},
    {"_exit"},
    {"_expf"},
    {"_fclose"},
    {"_fcntl"},
    {"_feof"},
    {"_ferror"},
    {"_fflush"},
    {"_fgets"},
    {"_floorf"},
    {"_fmod"},
    {"_fopen"},
    {"_fprintf"},
    {"_fputc"},
    {"_fputs"},
    {"_fread"},
    {"_free"},
    {"_freopen"},
    {"_frexp"},
    {"_fscanf"},
    {"_fseek"},
    {"_ftell"},
    {"_fwrite"},
    {"_getc"},
    {"_getenv"},
    {"_gettimeofday"},
    {"_glActiveTexture"},
    {"_glBindBuffer"},
    {"_glBindFramebufferOES"},
    {"_glBindRenderbufferOES"},
    {"_glBindTexture"},
    {"_glBlendFunc"},
    {"_glBufferData"},
    {"_glCheckFramebufferStatusOES"},
    {"_glClear"},
    {"_glClearColor"},
    {"_glClientActiveTexture"},
    {"_glColor4f"},
    {"_glColorPointer"},
    {"_glCompressedTexImage2D"},
    {"_glDeleteBuffers"},
    {"_glDeleteFramebuffersOES"},
    {"_glDeleteRenderbuffersOES"},
    {"_glDeleteTextures"},
    {"_glDepthFunc"},
    {"_glDepthMask"},
    {"_glDisable"},
    {"_glDisableClientState"},
    {"_glDrawArrays"},
    {"_glDrawElements"},
    {"_glEnable"},
    {"_glEnableClientState"},
    {"_glFramebufferRenderbufferOES"},
    {"_glFramebufferTexture2DOES"},
    {"_glFrontFace"},
    {"_glGenBuffers"},
    {"_glGenFramebuffersOES"},
    {"_glGenRenderbuffersOES"},
    {"_glGenTextures"},
    {"_glGetIntegerv"},
    {"_glGetRenderbufferParameterivOES"},
    {"_glLightfv"},
    {"_glLineWidth"},
    {"_glLoadMatrixf"},
    {"_glMaterialfv"},
    {"_glMatrixMode"},
    {"_glNormalPointer"},
    {"_glPixelStorei"},
    {"_glRenderbufferStorageOES"},
    {"_glScissor"},
    {"_glTexCoordPointer"},
    {"_glTexEnvi"},
    {"_glTexImage2D"},
    {"_glTexParameteri"},
    {"_glTexSubImage2D"},
    {"_glVertexPointer"},
    {"_glViewport"},
    {"_gmtime"},
    {"_ldexp"},
    {"_localeconv"},
    {"_localtime"},
    {"_log10f"},
    {"_logf"},
    {"_longjmp"},
    {"_lseek"},
    {"_malloc"},
    {"_memchr"},
    {"_memcmp"},
    {"_memcpy"},
    {"_memmove"},
    {"_memset"},
    {"_mktime"},
    {"_modf"},
    {"_pow"},
    {"_printf"},
    {"_pthread_create"},
    {"_pthread_exit"},
    {"_pthread_getschedparam"},
    {"_pthread_join"},
    {"_pthread_mutex_destroy"},
    {"_pthread_mutex_init"},
    {"_pthread_mutex_lock"},
    {"_pthread_mutex_trylock"},
    {"_pthread_mutex_unlock"},
    {"_pthread_mutexattr_destroy"},
    {"_pthread_mutexattr_init"},
    {"_pthread_mutexattr_settype"},
    {"_pthread_setschedparam"},
    {"_rand"},
    {"_read"},
    {"_realloc"},
    {"_remove"},
    {"_rename"},
    {"_sched_yield"},
    {"_select"},
    {"_setjmp"},
    {"_setlocale"},
    {"_setvbuf"},
    {"_sin"},
    {"_sinf"},
    {"_sinhf"},
    {"_snprintf"},
    {"_sprintf"},
    {"_srand"},
    {"_strcasecmp"},
    {"_strcat"},
    {"_strchr"},
    {"_strcmp"},
    {"_strcoll"},
    {"_strcpy"},
    {"_strcspn"},
    {"_strerror"},
    {"_strftime"},
    {"_strlen"},
    {"_strncat"},
    {"_strncmp"},
    {"_strncpy"},
    {"_strpbrk"},
    {"_strrchr"},
    {"_strtod"},
    {"_strtok"},
    {"_strtol"},
    {"_strtoul"},
    {"_system"},
    {"_tan"},
    {"_tanf"},
    {"_tanhf"},
    {"_time"},
    {"_tmpfile"},
    {"_tmpnam"},
    {"_ungetc"},
    {"_usleep"},
    {"_vsprintf"},
}};

inline constexpr std::size_t kProviderCount = kProviders.size();

inline std::vector<std::string> missingProviders(const ShimRegistry &registry) {
    std::vector<std::string> missing;
    for (const auto &provider : kProviders) {
        if (!registry.resolve(provider.symbol).has_value())
            missing.emplace_back(provider.symbol);
    }
    return missing;
}

} // namespace radek::compat_runtime::ndk_import_catalog
